### ISSUE TITLE
no bot connected

### ISSUE THREAD

**Issue by Hoangdepzaivcl** [TryZeroOne/Contagio#2]
Bot don't go contagio

**Comment by Hoangdepzaivcl** [comment]
> Bot don't go contagio

**Comment by Hoangdepzaivcl** [comment]
![Uploading IMG_0180.jpeg…]()
![Uploading IMG_0181.jpeg…]()

**Comment by TryZeroOne** [comment]
give more information

**Comment by TheCarlJ** [comment]
> Bot don't go contagio

my devices connect, you probably did something wrong
