### ISSUE TITLE
Unable to generate payload

### ISSUE THREAD

**Issue by ghost** [TryZeroOne/Contagio#4]
after running "make d" and done, then i ran "make payload", but this is what came up, in previous versions it was running normally.
![Screenshot 2023-06-26 183349](https://github.com/TryZeroOne/Contagio/assets/132572482/c57a3f0c-691c-42cb-ad05-346f34e1bf0f)

**Comment by ghost** [comment]
problem fixed, tried to remove this section in line 54 and 55 in config.toml file. I don't know why but the problem is solved.
![Screenshot 2023-06-26 184330](https://github.com/TryZeroOne/Contagio/assets/132572482/97676cb6-c6eb-4328-b618-a79762f5b4bf)

**Comment by TryZeroOne** [comment]
Thank you for the info, error fixed
