### ISSUE TITLE
Cant get bots connected/loaded

### ISSUE THREAD

**Issue by LexiDun** [TryZeroOne/Contagio#6]
Probably just messing something up on my end. Anyone mind sharing a example of running the loader?
I'm trying.
go run loader.go .txtfile

**Comment by LexiDun** [comment]
Im a dipshit solved it but now i'm running into another problem as bots are loading.  Bots are loading and getting registered on the screen but not appearing on the c2 
https://imgur.com/a/P49tUMK
https://imgur.com/a/P49tUMK

**Comment by TryZeroOne** [comment]
Most likely these bots are either already locked or they're shitty or you've setup the config incorrectly
