### ISSUE TITLE
Bot not loading

### ISSUE THREAD

**Issue by zhindins** [TryZeroOne/Contagio#7]
Hello,

I installed the Contagio following the README + Video. 
Everything worked! I didn't have many problems. However, when adding the bots, they are loaded but the CNC does not detect them.

By the way, I already entered my PAYLOAD in loader.go file

Here is the server output:

Print 01 => https://prnt.sc/xpk8o1e5nOzn
Print 02 => https://prnt.sc/GRDsd6axH9Sc
Print 03 => https://prnt.sc/z_RcPSSfEdV-

There are no errors but the bots are not loaded. What can it be? I am 100% willing to hand over my server login and password for the author to investigate, if necessary. Text me on Telegram => @johnzhins

Thank you very much.

**Comment by zhindins** [comment]
Also, the video was deleted by YT. Consider uploading it somewhere better than YT

**Comment by TryZeroOne** [comment]
hello! I need some bots to check

**Comment by zhindins** [comment]
> hello! I need some bots to check

https://pastebin.com/raw/BKvKsW6T
Telnet bots. Seems that generated .bin files are too big and bots cannot download it. Take several seconds to download and then it crash. Also, some bots download it after +- 1 minute and can't execute the bin, the output is "Killed" (check 111.33.134.171:23 admin:123456)

**Comment by TryZeroOne** [comment]
these bots already locked 
![image](https://github.com/TryZeroOne/Contagio/assets/132102370/bd7daf66-2c18-4bca-9954-c38ecefdfc52)

**Comment by zhindins** [comment]
I'm using telnet-bruter for scanning, some of those bots lasts for few hours then they die. This list I sent you, at least 50% still working, try to load them using the loader you did and you will see that some of them still working, the problem is that the bin is too big. I believe that this is the problem.

I ran my scanner for almost 24 hours and generated almost 1500 bots, and none of them worked in your loader. If you want, text me on tg so I can show you some evidences

**Comment by TryZeroOne** [comment]
bro, its shitty bots. They can't open binary files

**Comment by zhindins** [comment]
Your bot is the best currently, it's neat, functional and configurable. It has everything the others don't. Most out there are variations of mirai and qbot. But it doesn't make sense for your bot not to load the bots that are scanned over the internet, it makes this project so perfect unusable.

If you really want to fix this problem and make this project more important, I recommend that you download telnet-scanner from github and run it for at least 3 hours, you will capture some bots that work in both mirai and qbot and their variations, but do not work in your project. Try doing comparisons and maybe you'll find some way to optimize and allow your code to load these bots.
